Issue 105 Branch: trunk Release: M3
Description:
------------

     The runtime-conf.xml did not have the correct name
     of the database for the runtime use of PROPEL. The 
     execution of propel generated the following Exception:
   
PropelException:  [wrapped: SQLSTATE[42S02]: Base table or view not found: 1146
Table 'infinitymetricsm303.user' doesn't exist]
   
Details:
--------

* trunk/propel/runtime-conf.xml
 
    Renaming the database name for the execution. Whenever
    the database structure changes, both runtime-conf.xml
    and build.properties should change too.